spring:
  datasource:
    url: jdbc:mysql://eshop-mysql:3306/eshops?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: eshop-redis
      port: 6379
  elasticsearch:
    uris: http://eshop-es:9200